version: "2.1"
services:
  chrome:
    build: .
    image: tetraphobia/uivision-docker
    container_name: chrome
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - CHROME_CLI=--load-extension=/uivision \
          --no-default-browser-check \
          --disable-fre \
          --no-first-run \
          file:///html/uiv.html?direct=1
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped
