version: "2.1"
services:
  chromium:
    build: .
    container_name: chromium
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - CHROME_CLI=--load-extension=/uiv https://google.com
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped
